---
- name: install postgres
  apt: name={{ item }} state=present
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: create db
  postgresql_db: name={{ postgres.dbname }}
  become_user: postgres

- name: create db user
  postgresql_user:
    db: "{{ postgres.dbname }}"
    name: "{{ postgres.username }}"
    password: "{{ postgres.password }}"
  become_user: postgres
