default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  reconnect: true
  pool: 5

development:
  <<: *default
  database: zero_development

test:
  <<: *default
  reconnect: false
  database: zero_test
